apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.name }}
  namespace: {{ default .Release.Namespace .Values.namespace }}
  labels:
    app: {{ .Values.name }}
    version: {{ .Values.image.tag }}
    env: {{ .Values.env }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ .Values.name }}
      env: {{ .Values.env }}
  template:
    metadata:
      labels:
        app: {{ .Values.name }}
        version: {{ .Values.image.tag }}
        env: {{ .Values.env }}
    spec:
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.registry }}/{{ .Values.image.name }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          env:
            - name: DATABASE_MONGODB_DBNAME
              value: {{ default "chegaai" .Values.environment.DATABASE_MONGODB_DBNAME | quote }}
            - name: DATABASE_MONGODB_URI
              value: {{ required "Mongodb URI is required" .Values.environment.DATABASE_MONGODB_URI | quote }}
            - name: JWT_SECRET
              value: {{ required "JWT Secret is required" .Values.environment.JWT_SECRET | quote }}
            - name: JWT_AUDIENCE
              value: {{ required "JWT Audience is required" .Values.environment.JWT_AUDIENCE | quote }}
            - name: JWT_ISSUER
              value: {{ required "JWT Issuer is required" .Values.environment.JWT_ISSUER | quote }}
            - name: MICROSERVICES_GROUP_URL
              value: {{ default (tpl "http://ms-groups.{{.Release.Namespace}}.svc.cluster.local" .) .Values.environment.MICROSERVICES_GROUP_URL | quote }}
            - name: CLIENTS_MAIL_URL
              value: {{ default (tpl "http://zaqar.{{.Release.Namespace}}.svc.cluster.local" .) .Values.environment.CLIENTS_MAIL_URL | quote }}
            - name: CLIENTS_PROFILES_URL
              value: {{ default (tpl "http://ms-profiles.{{.Release.Namespace}}.svc.cluster.local" .) .Values.environment.CLIENTS_PROFILES_URL | quote }}
            - name: NODE_ENV
              value: {{.Release.Namespace}}
          ports:
            - name: http
              containerPort: 3000
              protocol: TCP
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
      imagePullSecrets:
        - name: registry-credentials
